"""empty message

Revision ID: 496b9489211e
Revises: d91b2c9c21e4
Create Date: 2021-03-26 16:29:32.838914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496b9489211e'
down_revision = 'd91b2c9c21e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_task')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_perfect')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_perfect', sa.BOOLEAN(), nullable=True))

    op.create_table('_alembic_tmp_task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=6), nullable=True),
    sa.Column('is_done', sa.BOOLEAN(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('is_done IN (0, 1)'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
